#!/bin/sh

scriptFile=$(readlink -f "$0")
scriptDir=$(dirname $scriptFile)

function linkConfig() {
	createHomeDir $(dirname $1)
	mkdir -p ~/$1
	ln -sf $scriptDir/$1 ~/$1
}

linkConfig .vimrc
linkConfig .zshrc
linkConfig .bashrc
linkConfig .bash_profile
linkConfig .config/sway/config
linkConfig .config/kitty/dracula.conf
linkConfig .config/kitty/kitty.conf
linkConfig .config/alacritty/alacritty.yml
linkConfig .config/swaylock/config
linkConfig .config/waybar/config
linkConfig .config/waybar/style.css
